---
title: "Yes I have a blog"
description: |
  A short description of the post.
author:
  - name:John Fair
date: 04-29-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
#First Blog post
My senior project is a twofold assignment for me. I am a transfer student to BYU—Idaho and so I have taken a patchwork of courses and at my old school they did not put an emphasis on learning the Python language. During my internship, I found out that this fact would put me a disadvantage from other new graduates, so I decided to utilize and bulk up my understanding of the language during my project.

I have recently been interested in learning more about stock and investments. I was taught the concept of Time Series and find that this could be a great topic with real life applications in my future. I am going to use stock datasets for 6-7 of the most well-known companies: Apple, Amazon, Disney, Google, Microsoft, Nike, and Walmart. My main question is figuring out which of these companies would the best choice to invest in and use time series methodology to see where these stocks could go in the future.

While researching time series or forecasting for stock predictions the one coding tool that was a fundamental beginning point is Application Programming Interface (API). To simplify what API’s do is that they create a pathway to recall the most up-to-date data from a specific website. When using an API with stock predictions, it updates the data to real time and gives you the current information. This kind of tool will be beneficial when trying to find out which stock is the best to invest in.

I have found so far that python is a little bit more user friendly and inclusive with package options to help assist different projects. When researching API’s, python has a package called “YFinance.” It is an open-source library to allows you to access financial data available on Yahoo Finance. The package is very streamlined. All you need to do is create a ticker object for a particular stock or list of stock tickers and call all the methods on this object. As seen below:

One crowning feature of yfinance is that you can get highly concentrated data, all the way down to 5 minutes, 3 minutes and even 1 minute data! The full range of intervals available are:

1m, 2m, 5m, 15m, 30m, 60m, 90m, 1h, 1d, 5d, 1wk, 1mo, 3mo

One thing to note is that the 1m data is only retrievable for the latest 7 days.
Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.


